/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jhjbppalohqnhofnpoov"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoamJwcGFsb2hxbmhvZm5wb292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzUwOTEsImV4cCI6MjA3MTIxMTA5MX0.-ocd73Q8Mx9iKkx5-UDnxibWl6kVIflhRTt-nNhqe7Y"